# Create a new comment
POST http://localhost:3003/api/comments HTTP/1.1
Content-Type: application/json

{
  "text": "This is a new comment.",
  "publicationId": "798efa44-670a-4769-ad20-1531aaa2f18c",
  "authorId": "64c7e9594191fd8963465142"
}

###

# Get comments by publication ID with limit
GET http://localhost:3003/api/comments/798efa44-670a-4769-ad20-1531aaa2f18c HTTP/1.1

###

# Get new comments after lastCommentId with limit
GET http://localhost:3003/api/comments/798efa44-670a-4769-ad20-1531aaa2f18c/next/64c7fe8e660070b372aca467?limit=1 HTTP/1.1
Content-Type: application/json

###

# Delete comment by ID
DELETE  http://localhost:3003/api/comments/64c7f6280568bcae92d79fc8 HTTP/1.1

###
